---
title: "Class06"
author: "Jiawei Xu"
format: pdf
editor: visual
---

```{r}
student1 <- c(100, 100, 100, 100, 100, 100, 100, 90)
student2 <- c(100, NA, 90, 90, 90, 90, 97, 80)
student3 <- c(90, NA, NA, NA, NA, NA, NA, NA)

```

```{r}
#for grading the student1, who does not have NA
which.min(student1)
student1[-which.min(student1)]
mean(student1[-which.min(student1)])
```

```{r}
# for students that have NA scores, NA needs to be removed first.
student2_temp <- student2
student2_temp[is.na(student2_temp)] <- 0   # assign 0 to NA
student2_temp
mean(student2_temp[-which.min(student2_temp)])
```

```{r}
student3_temp <- student3
student3_temp[is.na(student3_temp)] <- 0
student3_temp
mean(student3_temp[-which.min(student3_temp)])
```

```{r}
# write r function grade()
grade <- function(student_grade){
  student_grade_temp <- student_grade
  student_grade_temp <- as.numeric(student_grade_temp)
  student_grade_temp[is.na(student_grade_temp)] <- 0
  mean(student_grade_temp[-which.min(student_grade_temp)])
}

```

```{r}
# grade() fucntion test
grade(student1)
grade(student2)
grade(student3)
```

```{r}
# input csv file
scores <-  read.csv("https://tinyurl.com/gradeinput", row.names = 1)

result <- apply(scores, 1, grade)
result


# Q2 Who is the top scoring student overall in the gradebook?
which.max(result)
# student 18 is the top scoring student
```

```{r}
# Q3. From your analysis of the gradebook, which homework was toughest on students 
# (i.e. obtained the lowest scores overall?
apply(scores, 2, mean, na.rm = T)
which.min(apply(scores, 2, mean, na.rm = T))
# HW3 was toughest on students
```

```{r}
#Q4. From your analysis of the gradebook, which homework was most predictive of overall 
# score (i.e. highest correlation with average grade score)?
mask_Q4 <- scores
mask_Q4[is.na(mask_Q4)] <- 0
cor(result, mask_Q4)
apply(mask_Q4, 2, cor, y = result)
# HW5 was the most predictive
```
